"""Large first/last name pools so many Copley test identities stay unique."""

FIRST_NAMES = [
    "Aaliyah", "Aaron", "Abigail", "Adam", "Adrian", "Aisha", "Alana", "Albert",
    "Alejandro", "Alex", "Alexa", "Alice", "Alicia", "Amina", "Amir", "Amy",
    "Andrea", "Andre", "Angela", "Anita", "Anna", "Anthony", "Aria", "Ariana",
    "Arthur", "Ava", "Avery", "Beatrice", "Ben", "Bianca", "Brian", "Brittany",
    "Caleb", "Camila", "Carlos", "Carmen", "Caroline", "Carter", "Cecilia", "Charles",
    "Chloe", "Christina", "Christopher", "Clara", "Colin", "Connor", "Cora", "Daniel",
    "David", "Delia", "Derek", "Diana", "Diego", "Dina", "Dominic", "Elena",
    "Elias", "Eliza", "Ella", "Elliot", "Elsa", "Emily", "Emma", "Eric",
    "Eva", "Evan", "Farah", "Farid", "Fatima", "Felix", "Fiona", "Francesca",
    "Gabriel", "Gabriela", "George", "Grace", "Greta", "Hana", "Hannah", "Harper",
    "Hassan", "Helen", "Henry", "Hugo", "Ibrahim", "Imogen", "Ines", "Iris",
    "Isaac", "Isabel", "Ivan", "Ivy", "Jack", "Jacob", "Jade", "James",
    "Jasmine", "Jason", "Jayden", "Jessica", "Joanna", "Joel", "Johan", "Jonah",
    "Jonathan", "Jordan", "Joseph", "Joshua", "Julia", "Julian", "Juliana", "Kai",
    "Kara", "Karen", "Karim", "Kate", "Katherine", "Keiko", "Kevin", "Kira",
    "Laura", "Lauren", "Layla", "Leah", "Leila", "Leo", "Leon", "Liam",
    "Lila", "Lily", "Lina", "Logan", "Lucia", "Luca", "Luis", "Luna",
    "Maddox", "Maeve", "Marco", "Marcus", "Maria", "Marina", "Mario", "Marisol",
    "Mark", "Martha", "Martin", "Mateo", "Matthew", "Maya", "Megan", "Mia",
    "Michael", "Michelle", "Miguel", "Mila", "Mina", "Mohamed", "Monica", "Nadia",
    "Naomi", "Natalia", "Nathan", "Nia", "Nicholas", "Nicole", "Niko", "Nina",
    "Noah", "Noelle", "Nora", "Nour", "Olive", "Oliver", "Olivia", "Omar",
    "Ophelia", "Oscar", "Owen", "Pablo", "Paige", "Parker", "Patricia", "Patrick",
    "Paul", "Paula", "Pavel", "Peter", "Philip", "Phoebe", "Pilar", "Priya",
    "Quinn", "Rafael", "Raina", "Raj", "Rebecca", "Reina", "Rene", "Riley",
    "Robert", "Rosa", "Rose", "Ruby", "Ryan", "Sabrina", "Sadie", "Samir",
    "Samuel", "Sandra", "Sara", "Sarah", "Sean", "Sebastian", "Selena", "Serena",
    "Sofia", "Soren", "Stella", "Stephen", "Summer", "Talia", "Tariq", "Taylor",
    "Teresa", "Theo", "Thomas", "Tomas", "Uma", "Valentina", "Valerie", "Vera",
    "Victor", "Victoria", "Vincent", "Violet", "Wendy", "Wesley", "William", "Willow",
    "Xavier", "Yara", "Yasmin", "Yusuf", "Zachary", "Zane", "Zara", "Zoe",
]

LAST_NAMES = [
    "Abbott", "Adams", "Adeyemi", "Aguilar", "Ahmed", "Alvarez", "Anderson", "Andrade",
    "Armstrong", "Aoki", "Bailey", "Baker", "Banerjee", "Barrett", "Bennett", "Bergstrom",
    "Bishop", "Boyd", "Brooks", "Brown", "Bryant", "Campbell", "Castro", "Castillo",
    "Chambers", "Chan", "Chavez", "Chen", "Cho", "Clark", "Cohen", "Cole",
    "Collins", "Contreras", "Cooper", "Cox", "Cruz", "Cunningham", "Diaz", "Dixon",
    "Dominguez", "Douglas", "Duarte", "Edwards", "Ellis", "Espinoza", "Evans", "Everett",
    "Fernandez", "Flores", "Foster", "Fujimoto", "Garcia", "Gibson", "Gomez", "Gonzalez",
    "Gordon", "Graham", "Gray", "Green", "Griffin", "Guerrero", "Gupta", "Gutierrez",
    "Haddad", "Hall", "Hansen", "Harris", "Hassan", "Hayes", "Henderson", "Hernandez",
    "Hill", "Howard", "Hughes", "Ibrahim", "Inoue", "Iversen", "Jackson", "James",
    "Jensen", "Jimenez", "Johnson", "Jones", "Jordan", "Joseph", "Kaur", "Kelly",
    "Khan", "Kim", "King", "Kowalski", "Kumar", "Lambert", "Larson", "Lee",
    "Lewis", "Lindqvist", "Long", "Lopez", "Luna", "Lynch", "Mahmoud", "Marquez",
    "Marshall", "Martin", "Martinez", "Mason", "Medina", "Mendez", "Miller", "Mitchell",
    "Moore", "Morales", "Moreau", "Morgan", "Morris", "Murphy", "Myers", "Nakamura",
    "Nash", "Navarro", "Nelson", "Nguyen", "Nielsen", "Nkrumah", "Okoye", "Olson",
    "Ortiz", "Owens", "Palacios", "Parker", "Patel", "Perez", "Perry", "Peterson",
    "Phillips", "Powell", "Price", "Quinn", "Ramos", "Reed", "Reyes", "Richardson",
    "Rivera", "Roberts", "Robinson", "Rodriguez", "Rogers", "Romero", "Ross", "Ruiz",
    "Russell", "Saito", "Salazar", "Sanchez", "Sanders", "Santos", "Schmidt", "Scott",
    "Sharma", "Silva", "Simmons", "Singh", "Smith", "Soto", "Stewart", "Sullivan",
    "Tanaka", "Taylor", "Thomas", "Thompson", "Torres", "Tran", "Turner", "Ullah",
    "Vargas", "Vasquez", "Vega", "Wagner", "Walker", "Wallace", "Walsh", "Wang",
    "Ward", "Washington", "Watson", "White", "Williams", "Wilson", "Wong", "Wright",
    "Xiao", "Yamamoto", "Yang", "Yilmaz", "Young", "Zahra", "Zimmerman", "Zuniga",
]
